name: Captain's Changelog
description: Scrawlins o' Cap'n Nick Shvelidze
highlighter: 'pygments'
timezone: Asia/Tbilisi
permalink: /:year/:title
markdown: kramdown
baseurl: /
url: http://blog.pirrate.me
excerpt_separator: "<!--more-->"

disqus_shortname: pirrate
