name: Captain's Changelog
description: Scrawlins o' Cap'n Nick Shvelidze
pygments: true
timezone: Asia/Tbilisi
relative_permalinks: true
permalink: /:year/:title
markdown: maruku
baseurl: /
url: http://blog.pirrate.me
excerpt_separator: "<!--more-->"

disqus_shortname: pirrate
